zeno-ml/zeno-client

poetry.lock, zeno_client/client.py
Always enforce trusted requests, required for our HTTPS endpoints.
=> fix: trusted requests

pyproject.toml, zeno_client/client.py
Correct default endpoint, make compatible with old pydantic.
=> fix: fix endpoint and pydantic 1.0 fix

README.md
This fixes a typo in the README.
- NA
=> fix: code typo in README.md

README.md
Don't think we should put a csv here and explain what it needs to contain. csv --> df is pretty trivial anyway so should be fine and less confusing.
=> docs: move from csv example to dataframe

README.md
Fix inconsistent quotes in README.md
- NA
=> fix: fix inconsistent quotes in README.md

README.md
set a default instance view for docs
=> fix: update docs for instance view

zeno_client/client.py
fix ZEN-168
Requires https://github.com/zeno-ml/zeno-hub/pull/232
=> docs: print the link to the project after creation

zeno_client/client.py, zeno_client/exceptions.py
Checks whether the version of the Zeno-Client is at least what the backend needs on client initialization.
fix ZEN-195
=> feat: add check for version number on client initialization

examples/simple_project.ipynb, zeno_client/client.py
=> refactor: make most python param names mandatory to be specified

zeno_client/client.py
=> fix: fix iloc issues

zeno_client/client.py
Remove unused options from project creation.
MUST accompany a bump in minimum version in the hub in this PR: https://github.com/zeno-ml/zeno-hub/pull/306
Fix ZEN-240
=> fix: remove old project options

pyproject.toml
Update to 0.1.9 with new updates.
=> build: version bump

zeno_client/client.py
=> feat: delete systems

zeno_client/client.py
=> fix: url encode project url

pyproject.toml
=> build: v0.1.10

pyproject.toml, zeno_client/client.py
Support tabular data (no view & no data_column) and support dict as view option.
Fix ZEN-292
=> feat: support no view & view dict

.github/workflows/ci.yml, poetry.lock, pyproject.toml, zeno_client/client.py, zeno_client/util.py
Data munging to convert structs to JSON strings. Lets you directly work with dict columns.
Also update ruff formatting and get_client to use `name` `project` and avoid issues with slashes and syntax.
Fix ZEN-317
=> feat: dict column upload

zeno_client/client.py
=> fix: update url displayed after project creation

pyproject.toml, zeno_client/util.py
=> fix: allow upload string list

zeno_client/client.py
I think 10 is too few in almost all cases.
=> feat: up samples per page to be 30 by default
